### ISSUE TITLE
Negative points are not possible

### ISSUE THREAD

**Issue by mr-gosh** [rengolin/cardgamescores#1]
In "Doppelkopf" many people count positive for the two winners and negative for the two loosers... This doesnt Seen to be possible

**Comment by rengolin** [comment]
Indeed, it still adds up the total. I'll look into it.

**Comment by mr-gosh** [comment]
when do you think will this come live?

**Comment by rengolin** [comment]
I need to check with fdroid, but I believe it's just a matter of tagging the master branch, and they will rebuild.

**Comment by rengolin** [comment]
@mr-gosh, I have fixed all bugs and tagged v1.1, which should trigger a build on F-Droid's side, and an update soon.
