### ISSUE TITLE
Setting score to win to 0 crashes the app

### ISSUE THREAD

**Issue by mr-gosh** [rengolin/cardgamescores#2]
Setting the score to win to zero (so you can play on and on) crashes the APP...

**Comment by rengolin** [comment]
Hi @mr-gosh,

Sorry for the delay. I just tested it here and I don't get the crash. But it also doesn't let you play on and on, but instead, wins/loses instantly.

Maybe I should make a check-box if you want or not a final score, that'd solve both problems.

**Comment by mr-gosh** [comment]
good idea - that would solve this...
